apiVersion: v1
kind: Service
metadata:
  name: zeebe
  labels:
    app: zeebe
spec:
  clusterIP: None
  ports:
  - port: 26501
    name: client
  - port: 26502
    name: management
  - port: 26503
    name: replication
  - port: 26504
    name: subscription
  selector:
    app: zeebe